
work_dir: ./work_dir/ntu/xsub/msg3d_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /media/22905553/F020DDF820DDC5AE/Action_Dataset/Fall_detection_data/imbalanced/ntu120/xset/train_joint.npy
  label_path: /media/22905553/F020DDF820DDC5AE/Action_Dataset/Fall_detection_data/imbalanced/ntu120/xset/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  normalization: True
  random_choose: True
  window_size: 250

test_feeder_args:
  data_path: /media/22905553/F020DDF820DDC5AE/Action_Dataset/Fall_detection_data/imbalanced/ntu120/xset/val_joint.npy
  label_path: /media/22905553/F020DDF820DDC5AE/Action_Dataset/Fall_detection_data/imbalanced/ntu120/xset/val_label.pkl
  normalization: True
  debug: False
  random_choose: True
  window_size: 250
  
# model
model: model.model.Model
model_args:
  num_class: 2
  num_point: 25
  num_person: 2
  max_frame: 250
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
    max_hop: 4
# optim
weight_decay: 0.0005
base_lr: 0.05
step: [10, 20, 30, 40]

# training
num_epoch: 20
device: [0]
batch_size: 64
forward_batch_size: 32
test_batch_size: 64
nesterov: True

#weights: /home/uniwa/students3/students/22905553/linux/phd_codes/Fall_detection/ntu_xsub/weights/weights-15-315.pt
#weights: /home/uniwa/students3/students/22905553/linux/phd_codes/Fall_detection/ntu120_xset_F/weights/weights-30-450.pt
#checkpoint: /home/uniwa/students3/students/22905553/linux/phd_codes/Fall_detection/ntu120_xset_F/checkpoints/checkpoint-30-fwbz32-450.pt



