
work_dir: ./work_dir/ntu/xsub/msg3d_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: //media/22905553/F020DDF820DDC5AE/Action_Dataset/Fall_detection_data/imbalanced/ntu120/xsub/train_joint.npy
  label_path: /media/22905553/F020DDF820DDC5AE/Action_Dataset/Fall_detection_data/imbalanced/ntu120/xsub/train_label.pkl
  debug: False
  normalization: True
  random_choose: True
  window_size: 250

test_feeder_args:
  data_path: /media/22905553/F020DDF820DDC5AE/Action_Dataset/Fall_detection_data/imbalanced/ntu120/xsub/val_joint.npy
  label_path: /media/22905553/F020DDF820DDC5AE/Action_Dataset/Fall_detection_data/imbalanced/ntu120/xsub/val_label.pkl
  debug: False
  normalization: True
  random_choose: True
  window_size: 250
  
# model
model: model.model.Model
model_args:
  num_class: 2
  num_point: 25
  num_person: 2
  max_frame: 250
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
    max_hop: 4
# optim
weight_decay: 0.0005
base_lr: 0.05
step: [10, 20, 30, 40]

# training
num_epoch: 20
device: [0]
batch_size: 64
forward_batch_size: 32
test_batch_size: 64
nesterov: True

#weights: /home/uniwa/students3/students/22905553/linux/phd_codes/My_part_based_convolution/ntu_test_v9/weights/weights-1-626.pt

#checkpoint: /home/uniwa/students3/students/22905553/linux/phd_codes/My_part_based_convolution/ntu_test_v9/checkpoints/checkpoint-1-fwbz32-626.pt



